import Head from 'next/head'
import ListingsFeed from '../component/ListingsFeed'
import Nav from '../component/Nav'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NPTest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Overpass&display=swap" rel="stylesheet" />
      </Head>

      <Nav />

      <ListingsFeed />

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
